name: drops
description: "A pacakge for showing alerts like the one used when copying from pasteboard or connecting Apple pencil and the alert shown on iPhones when using the silent toggle."
version: 0.0.5
homepage: https://github.com/MaherSafadii/Drops-Flutter
repository: https://github.com/MaherSafadii/Drops-Flutter

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



